name: Bug Report
description: Create a bug report to help improve the datapacks
title: "[Bug]: "
labels: ["bug"]
assignees:
  - tristankechlo
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is, and how it appeared.
      placeholder: |
        Tell us what happened!
        How did you produce the bug?
        What should have happened?
    validations:
      required: true
  - type: input
    id: minecraftversion
    attributes:
      label: Minecraft Version
      description: The minecraft version you are using.
      placeholder: ex. 1.20
    validations:
      required: true
  - type: input
    id: datapackversion
    attributes:
      label: Datapackversion
      description: What version of the datapack are you using? This can be the name of the datapack.
      placeholder: ex. NoMoreFloatingIslands-1.20.4-1.0.0.zip
    validations:
      required: true
  - type: dropdown
    id: modloader
    attributes:
      label: Modloader
      description: What modloader are you using?
      options:
        - Forge
        - Fabric
        - Neoforge
        - Quilt
        - Other
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here. If you have screenshots you can attach them here.
    validations:
      required: false
  - type: checkboxes
    id: checks
    attributes:
      label: Before submitting
      options:
        - label: I tested that the problem is caused by this datapack (the bug does not happen when removing this pack)
          required: true
        - label: I checked that there are no similar posts (open or closed) related to the this problem
          required: true
